# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdpdf" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "d582f2b0595753ac3b302ca136064c5ed82d17de55f0ee60b82f2f058480aed8"
      url "https://github.com/mfreydl/mdpdf/releases/download/v#{version}/mdpdf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3c9ee7978658d6bb511680530b807f56dadce023a423640fdce2eff6a05d9db0"
      url "https://github.com/mfreydl/mdpdf/releases/download/v#{version}/mdpdf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c70c98f8815d1871b6b5bbd6a04f1a4a115b0f768e74135140032131ce9c6889"
      url "https://github.com/mfreydl/mdpdf/releases/download/v#{version}/mdpdf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c604aa9b2d13ac709f265d81436921c9aa37656e092cb97877975458534ff0e5"
      url "https://github.com/mfreydl/mdpdf/releases/download/v#{version}/mdpdf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mdpdf"
  desc "Convert Markdown to PDF. One binary, pure Go, no browser required."
  homepage "https://github.com/mfreydl/mdpdf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdpdf"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdpdf"]
    end
  end

  # No zap stanza required

end
