# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdpdf" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "57e548c96d9e6bff6414bbb758e296d93cf2b09f5df3d3686f2f4a9b34b14998"
      url "https://github.com/mfreydl/mdpdf/releases/download/v#{version}/mdpdf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d9b5aebc998c2df8344774cdd8b0db734723515d29f741e744cfdcb9c5d3141"
      url "https://github.com/mfreydl/mdpdf/releases/download/v#{version}/mdpdf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "13d497f3fbeacb3d21ee3c0cbcb2809186f865d5944b20191d0d26c07031dd0c"
      url "https://github.com/mfreydl/mdpdf/releases/download/v#{version}/mdpdf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "49a2aa523277297f8f9f3782b3376aa2b0876f798042fac735f3e4a23b0de957"
      url "https://github.com/mfreydl/mdpdf/releases/download/v#{version}/mdpdf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mdpdf"
  desc "Convert Markdown to PDF. One binary, pure Go, no browser required."
  homepage "https://github.com/mfreydl/mdpdf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdpdf"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdpdf"]
    end
  end

  # No zap stanza required

end
