# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdpdf" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "07d0f3dfa8952581635d700733db30e34789558a6921e52594eefaf90019d507"
      url "https://github.com/mfreydl/mdpdf/releases/download/v#{version}/mdpdf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "816b9b6e359b97a290018acddd9f992fb32e94f1704eb7d77ae0f4a00646b92a"
      url "https://github.com/mfreydl/mdpdf/releases/download/v#{version}/mdpdf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "00c23d26d8b537ddccb348d58d2c6b1ad3b71c806c72f490d1e0e35fe787996c"
      url "https://github.com/mfreydl/mdpdf/releases/download/v#{version}/mdpdf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d83044fbb5055e8079764fc9dfd2bad75da0204cac780ebc3ab5e396d04aa56"
      url "https://github.com/mfreydl/mdpdf/releases/download/v#{version}/mdpdf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mdpdf"
  desc "Convert Markdown to PDF. One binary, pure Go, no browser required."
  homepage "https://github.com/mfreydl/mdpdf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdpdf"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdpdf"]
    end
  end

  # No zap stanza required

end
